"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { PaymentCase } from "@recoverai/domain";
import { Shell } from "../../components/shell";
import { PageTitle, StatusBadge } from "../../components/ui";
import { Search } from "../../components/icons";
import { api, inr, label, pct } from "../../lib/api";

export default function CasesPage() {
  const [cases, setCases] = useState<PaymentCase[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [category, setCategory] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void api<PaymentCase[]>("/cases?batchId=batch-2026&sort=recoverability").then(setCases).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load cases")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => cases.filter(item => (!status || item.status === status) && (!category || item.failureCategory === category) && (!search || `${item.customerName} ${item.externalPaymentId} ${item.failureCode}`.toLowerCase().includes(search.toLowerCase()))), [cases, search, status, category]);
  return <Shell>
    <PageTitle eyebrow="Recovery inventory" title="Payment cases" description="Inspect every failed payment from diagnosis through authorization and simulated outcome."/>
    {error && <div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="panel mb-4 flex flex-wrap items-center gap-3 p-3"><label className="flex min-w-64 flex-1 items-center gap-2 rounded-lg border border-line bg-white px-3 py-2 text-sm"><Search size={15} className="text-slate-400"/><input aria-label="Search payment cases" className="w-full border-0 bg-transparent outline-none" placeholder="Search customer, payment, or failure" value={search} onChange={event => setSearch(event.target.value)}/></label><select aria-label="Filter by status" className="rounded-lg border border-line bg-white px-3 py-2 text-xs" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option>{["FAILED", "RECOVERY_PLANNED", "RECOVERED", "ESCALATED", "STOPPED"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter by failure category" className="rounded-lg border border-line bg-white px-3 py-2 text-xs" value={category} onChange={event => setCategory(event.target.value)}><option value="">All failure categories</option>{["TRANSIENT_TECHNICAL", "CUSTOMER_ACTION_REQUIRED", "PAYMENT_METHOD_ISSUE", "AUTHENTICATION", "INSUFFICIENT_FUNDS", "PERMANENT_FAILURE", "RISK_OR_FRAUD", "UNKNOWN"].map(value => <option key={value}>{value}</option>)}</select><span className="ml-auto px-2 text-xs text-slate-400">{filtered.length} cases</span></div>
    <div className="panel overflow-hidden">{loading ? <div className="h-80 animate-pulse bg-slate-100"/> : filtered.length === 0 ? <div className="grid h-64 place-items-center text-center"><div><div className="text-sm font-semibold">No matching cases</div><p className="mt-1 text-xs text-slate-400">Clear the filters or reset the demo batch.</p></div></div> : <div className="scrollbar overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-[.08em] text-slate-400"><tr>{["Customer", "Amount", "Method", "Failure", "Recoverability", "Risk", "AI recommendation", "Status", "Recovered", ""].map(header => <th key={header} className="px-4 py-3 font-semibold">{header}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id} className={`border-t border-line transition hover:bg-slate-50/70 ${item.demoTags.length ? "bg-blue/[.025]" : ""}`}><td className="px-4 py-3"><div className="flex items-center gap-2"><span className="font-semibold">{item.customerName}</span>{item.demoTags.length > 0 && <span className={`badge ${item.demoTags.includes("GOLDEN_SUCCESS") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{item.demoTags.includes("GOLDEN_SUCCESS") ? "Golden A" : "Golden B"}</span>}</div><div className="mt-1 text-[10px] text-slate-400">{item.externalPaymentId}</div></td><td className="px-4 font-semibold">{inr(item.amount)}</td><td className="px-4"><span className="rounded bg-slate-100 px-2 py-1 font-medium">{item.paymentMethod}</span></td><td className="max-w-44 px-4"><div className="truncate font-medium">{label(item.failureCategory ?? "Pending")}</div><div className="mt-1 truncate text-[10px] text-slate-400">{item.failureCode}</div></td><td className="px-4"><div className="flex items-center gap-2"><div className="h-1.5 w-16 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue" style={{ width: pct(item.recoverabilityScore ?? 0) }}/></div><b>{item.recoverabilityScore === null ? "—" : pct(item.recoverabilityScore)}</b></div></td><td className="px-4"><div className="flex items-center gap-2"><i className={`h-2 w-2 rounded-full ${item.riskScore >= .75 ? "bg-red-500" : item.riskScore >= .4 ? "bg-amber-500" : "bg-emerald-500"}`}/><b>{pct(item.riskScore)}</b></div></td><td className="px-4">{item.aiDecision ? <StatusBadge value={item.aiDecision.recommendedAction}/> : <span className="text-slate-400">Not planned</span>}</td><td className="px-4"><StatusBadge value={item.status}/></td><td className="px-4 font-semibold text-emerald-700">{item.recoveredAmount ? inr(item.recoveredAmount) : "—"}</td><td className="px-4"><Link href={`/cases/${item.id}`} className="font-semibold text-blue">Inspect</Link></td></tr>)}</tbody></table></div>}</div>
  </Shell>;
}
