"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import type { PaymentCase } from "@recoverai/domain";
import { Shell } from "../../../components/shell";
import { PageTitle, StatusBadge } from "../../../components/ui";
import { AlertTriangle, Bot, ShieldCheck, Sparkles } from "../../../components/icons";
import { api, inr, label, pct } from "../../../lib/api";

export default function CaseDetail() {
  const { id } = useParams<{ id: string }>(); const [item, setItem] = useState<PaymentCase>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const refresh = useCallback(async () => { try { setItem(await api<PaymentCase>(`/cases/${id}`)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load case"); } }, [id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const invoke = async (operation: "plan" | "execute") => { setBusy(true); setError(""); try { if (operation === "plan") setItem(await api<PaymentCase>(`/cases/${id}/plan`, { method: "POST", body: "{}" })); else { const result = await api<{ payment: PaymentCase }>(`/cases/${id}/execute`, { method: "POST", body: "{}" }); setItem(result.payment); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Operation failed"); } finally { setBusy(false); } };
  if (!item) return <Shell>{error ? <div role="alert" className="panel p-8 text-center text-sm text-red-700">{error}<button onClick={() => void refresh()} className="ml-3 font-semibold">Retry</button></div> : <div className="panel h-96 animate-pulse bg-slate-100"/>}</Shell>;
  const isOverride = Boolean(item.policyDecision && (!item.policyDecision.approved || item.aiDecision?.recommendedAction !== item.policyDecision.finalAction));
  const goldenLabel = item.demoTags.includes("GOLDEN_SUCCESS") ? "Golden A · Intelligent recovery" : item.demoTags.includes("GOLDEN_GUARDRAIL") ? "Golden B · Guardrail override" : null;
  return <Shell>
    <PageTitle eyebrow={goldenLabel ?? item.externalPaymentId} title={`${item.customerName} · ${inr(item.amount)}`} description="Trace the failure, advisory AI proposal, policy authorization, execution, and simulated outcome." action={<div className="flex gap-2">{!item.aiDecision && item.status === "FAILED" && <button onClick={() => void invoke("plan")} disabled={busy} className="rounded-lg bg-blue px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Planning…" : "Create recovery plan"}</button>}{item.policyDecision?.approved && item.status === "RECOVERY_PLANNED" && <button onClick={() => void invoke("execute")} disabled={busy} className="rounded-lg bg-ink px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Executing…" : "Execute simulation"}</button>}</div>}/>
    {error && <div role="alert" className="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className={`mb-5 flex items-center justify-between gap-4 rounded-xl border p-4 ${isOverride ? "border-red-200 bg-red-50" : "border-blue/20 bg-blue/5"}`}><div className="flex items-center gap-3">{isOverride ? <AlertTriangle size={18} className="text-red-600"/> : <Sparkles size={18} className="text-blue"/>}<div><div className="text-sm font-semibold">{isOverride ? "AI proposal overridden by policy" : "Bounded agent decision"}</div><div className="mt-1 text-xs text-slate-500">No recommendation can execute until deterministic controls authorize it.</div></div></div><StatusBadge value={item.status}/></div>

    <section className="panel p-5"><div className="mb-4 flex items-center justify-between"><div><div className="eyebrow">Decision control flow</div><div className="mt-1 text-sm font-semibold">AI recommends. Policy authorizes. Executor obeys.</div></div><span className="badge bg-amber-50 text-amber-700">SIMULATION</span></div><div className="grid grid-cols-[1fr_36px_1fr_36px_1fr] items-stretch max-xl:grid-cols-1">
      <DecisionCard eyebrow="1 · AI RECOMMENDATION" icon={<Bot size={17}/>} tone="blue" title={item.aiDecision ? label(item.aiDecision.recommendedAction) : "Awaiting plan"}><p>{item.aiDecision?.reasoningSummary ?? "No recommendation has been generated."}</p>{item.aiDecision && <div className="mt-3 grid grid-cols-3 gap-2"><Mini name="Recoverable" value={pct(item.aiDecision.recoverability)}/><Mini name="Confidence" value={pct(item.aiDecision.confidence)}/><Mini name="Risk" value={pct(item.aiDecision.riskScore)}/></div>}</DecisionCard>
      <FlowArrow/>
      <DecisionCard eyebrow="2 · POLICY GATE" icon={<ShieldCheck size={17}/>} tone={isOverride ? "red" : "green"} title={item.policyDecision ? item.policyDecision.approved ? "Approved" : "Denied / overridden" : "Awaiting proposal"}><p>{item.policyDecision?.reason ?? "Policy has not evaluated an AI proposal."}</p>{item.policyDecision && <div className={`mt-3 rounded-lg px-3 py-2 text-[11px] font-semibold ${isOverride ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{item.policyDecision.rule}</div>}</DecisionCard>
      <FlowArrow/>
      <DecisionCard eyebrow="3 · FINAL AUTHORIZED ACTION" icon={<ShieldCheck size={17}/>} tone={isOverride ? "red" : "green"} title={item.policyDecision ? label(item.policyDecision.finalAction) : "Not authorized"}><p>{isOverride ? `AI proposed ${label(item.aiDecision?.recommendedAction ?? "none")}; policy retained control and selected ${label(item.policyDecision?.finalAction ?? "stop")}.` : item.policyDecision?.approved ? "This closed, typed action is authorized for the executor." : "No action can execute."}</p>{item.policyDecision && <div className="mt-3"><StatusBadge value={item.policyDecision.approved ? "APPROVED" : "OVERRIDDEN"}/></div>}</DecisionCard>
    </div></section>

    <div className="mt-5 grid grid-cols-3 gap-5 max-xl:grid-cols-1"><section className="panel p-5"><div className="eyebrow">Payment information</div><dl className="mt-4 space-y-3 text-xs">{[["Amount", inr(item.amount)], ["Method", item.paymentMethod], ["Customer", item.customerEmail], ["Retries", `${item.retryCount} / ${item.maxRetries}`], ["Created", new Date(item.createdAt).toLocaleString("en-IN")]].map(([name, value]) => <div key={name} className="flex justify-between gap-4"><dt className="text-slate-400">{name}</dt><dd className="m-0 text-right font-medium">{value}</dd></div>)}</dl></section><section className="panel p-5"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-amber-600"/><div className="eyebrow">Failure diagnosis</div></div><div className="mt-4 text-sm font-semibold">{label(item.failureCategory ?? "Pending diagnosis")}</div><p className="text-xs leading-5 text-slate-500">{item.diagnosis?.explanation ?? item.failureReason}</p><div className="mt-4 flex gap-2">{item.diagnosis && <><StatusBadge value={item.diagnosis.safeToRetry ? "SAFE_TO_RETRY" : "ACTION_REQUIRED"}/><span className="badge bg-slate-100 text-slate-600">{pct(item.diagnosis.confidence)} confidence</span></>}</div></section><section className="panel p-5"><div className="eyebrow">Simulation outcome</div><div className={`metric-number mt-4 text-3xl font-semibold ${item.recoveredAmount ? "text-emerald-700" : "text-slate-700"}`}>{inr(item.recoveredAmount)}</div><div className="mt-1 text-xs text-slate-400">Simulated recovered revenue; no live charge</div><div className="mt-5"><StatusBadge value={item.status}/></div></section></div>

    <section className="panel mt-5 p-5"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Immutable-style audit timeline</div><div className="mt-1 text-xs text-slate-400">Chronological evidence for every meaningful transition</div></div><span className="text-[11px] text-slate-400">{item.audit.length} events</span></div><div className="mt-5 space-y-0">{item.audit.map((event, index) => <div key={event.id} className="grid grid-cols-[18px_155px_1fr] gap-3 text-xs"><div className="flex flex-col items-center"><i className={`mt-1.5 h-2.5 w-2.5 rounded-full ${event.actor === "POLICY" ? "bg-emerald-500" : event.actor === "AI" ? "bg-blue" : "bg-slate-400"}`}/>{index < item.audit.length - 1 && <span className="h-full w-px bg-line"/>}</div><div className="pb-5 text-[10px] text-slate-400">{new Date(event.timestamp).toLocaleString("en-IN")}</div><div className="pb-5"><div className="flex items-center gap-2"><b>{label(event.eventType)}</b><span className="badge bg-slate-100 text-slate-500">{event.actor}</span><span className="badge bg-slate-100 text-slate-500">{event.mode}</span></div><p className="mb-0 mt-1 text-slate-500">{event.reason}</p></div></div>)}</div></section>
  </Shell>;
}

function FlowArrow() { return <div className="grid place-items-center text-xl font-light text-slate-300 max-xl:rotate-90">→</div>; }
function DecisionCard({ eyebrow, icon, tone, title, children }: { eyebrow: string; icon: React.ReactNode; tone: "blue" | "green" | "red"; title: string; children: React.ReactNode }) { const style = tone === "red" ? "border-red-200 bg-red-50/30 text-red-700" : tone === "green" ? "border-emerald-200 bg-emerald-50/30 text-emerald-700" : "border-blue/20 bg-blue/[.025] text-blue"; return <div className={`rounded-xl border p-4 ${style}`}><div className="flex items-center gap-2 text-[10px] font-bold tracking-[.1em]">{icon}{eyebrow}</div><div className="mt-4 text-lg font-semibold text-ink">{title}</div><div className="mt-2 text-xs leading-5 text-slate-500">{children}</div></div>; }
function Mini({ name, value }: { name: string; value: string }) { return <div className="rounded-lg bg-white/80 p-2 text-center"><div className="text-[9px] text-slate-400">{name}</div><b className="mt-1 block text-[11px] text-ink">{value}</b></div>; }
