"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { StrategyMetrics } from "@recoverai/domain";
import { Shell } from "../../components/shell";
import { PageTitle } from "../../components/ui";
import { api, inr, pct } from "../../lib/api";
import { Bot, RefreshCcw, ShieldCheck, Sparkles } from "../../components/icons";

type Comparison = { baseline?: StrategyMetrics; recoverai?: StrategyMetrics; additionalRevenue: number; attemptsReduced: number };

export default function CommandCenter() {
  const [batch, setBatch] = useState("batch-2026");
  const [base, setBase] = useState<StrategyMetrics>();
  const [recoverai, setRecoverai] = useState<StrategyMetrics>();
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("Seed 2026 is ready. Reset any time for a pristine run.");
  const [error, setError] = useState("");
  const loadComparison = useCallback(async () => { try { const result = await api<Comparison>(`/batches/${batch}/comparison`); setBase(result.baseline); setRecoverai(result.recoverai); } catch { /* Empty comparison is a valid first-run state. */ } }, [batch]);
  useEffect(() => { void loadComparison(); }, [loadComparison]);

  const generate = async () => { setBusy("reset"); setError(""); try { const result = await api<{ id: string; count: number }>("/batches/generate", { method: "POST", body: JSON.stringify({ count: 100, seed: 2026 }) }); setBatch(result.id); setBase(undefined); setRecoverai(undefined); setMessage(`${result.count} pristine deterministic cases loaded.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Reset failed"); } finally { setBusy(""); } };
  const run = async (kind: "baseline" | "recoverai") => { setBusy(kind); setError(""); try { const result = await api<StrategyMetrics>(`/batches/${batch}/run-${kind}`, { method: "POST", body: "{}" }); if (kind === "baseline") setBase(result); else setRecoverai(result); setMessage(`${kind === "baseline" ? "Naive baseline" : "RecoverAI"} completed against seed 2026.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Strategy run failed"); } finally { setBusy(""); } };
  const bothComplete = Boolean(base && recoverai);

  return <Shell>
    <PageTitle eyebrow="Deterministic experiment" title="Recovery command center" description="Reset, run both strategies, compare measured outcomes, then open the two stable demo cases." action={<button onClick={generate} disabled={Boolean(busy)} className="flex items-center gap-2 rounded-lg bg-blue px-4 py-2.5 text-xs font-semibold text-white shadow-sm disabled:opacity-50"><RefreshCcw size={14} className={busy === "reset" ? "animate-spin" : ""}/>Reset Demo · Seed 2026</button>}/>
    {error && <div role="alert" className="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="panel mb-5 flex items-center justify-between p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue/10 text-blue"><Sparkles size={17}/></span><div><div className="text-sm font-semibold">{message}</div><div className="mt-1 text-[11px] text-slate-400">Batch {batch} · common case outcomes · simulation only</div></div></div><div className="flex items-center gap-2 text-[11px] font-medium text-slate-500"><Step done label="Reset"/><span className="h-px w-5 bg-line"/><Step done={Boolean(base)} label="Baseline"/><span className="h-px w-5 bg-line"/><Step done={Boolean(recoverai)} label="RecoverAI"/></div></div>
    <div className="grid grid-cols-2 gap-5 max-lg:grid-cols-1"><Strategy title="Naive baseline" text="One immediate retry for every non-terminal, non-fraud eligible case." icon={<RefreshCcw size={19}/>} color="slate" metrics={base} onRun={() => run("baseline")} busy={Boolean(busy)} running={busy === "baseline"}/><Strategy title="RecoverAI" text="Diagnosis, next-best intervention, deterministic policy gate, then seeded outcome." icon={<Bot size={19}/>} color="blue" metrics={recoverai} onRun={() => run("recoverai")} busy={Boolean(busy)} running={busy === "recoverai"}/></div>
    <section className="panel mt-5 p-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-emerald-600"/><div className="text-sm font-semibold">Head-to-head simulated business impact</div></div>{bothComplete ? <div className="mt-5 grid grid-cols-5 gap-4 max-xl:grid-cols-2"><Metric name="Incremental revenue" value={inr(recoverai!.revenueRecovered - base!.revenueRecovered)} positive/><Metric name="Recovery lift" value={`${Math.round((recoverai!.recoveryRateByValue - base!.recoveryRateByValue) * 100)} pp`} positive/><Metric name="Attempts reduced" value={String(base!.attempts - recoverai!.attempts)} positive/><Metric name="Unsafe actions prevented" value={String(recoverai!.riskyActionsPrevented)}/><Metric name="Escalations" value={String(recoverai!.escalations)}/></div> : <div className="mt-5 rounded-lg border border-dashed border-slate-300 py-9 text-center text-sm text-slate-400">Run both strategies in either order. Each run restores the same initial population.</div>}</section>
    <section className="mt-5 grid grid-cols-2 gap-5 max-lg:grid-cols-1"><GoldenLink href="/cases/golden-success-2026" title="Golden A · Intelligent recovery" text="₹4,999 · transient issuer failure · approved retry · deterministic recovery" tone="success" ready={Boolean(recoverai)}/><GoldenLink href="/cases/golden-guardrail-2026" title="Golden B · Guardrail override" text="Retry limit reached · AI proposes retry · policy forces human review" tone="danger" ready={Boolean(recoverai)}/></section>
  </Shell>;
}

function Step({ done, label: text }: { done: boolean; label: string }) { return <span className={`flex items-center gap-1.5 ${done ? "text-emerald-700" : "text-slate-400"}`}><i className={`h-2 w-2 rounded-full ${done ? "bg-emerald-500" : "bg-slate-300"}`}/>{text}</span>; }
function Strategy({ title, text, icon, color, metrics, onRun, busy, running }: { title: string; text: string; icon: React.ReactNode; color: "blue" | "slate"; metrics?: StrategyMetrics; onRun: () => void; busy: boolean; running: boolean }) { return <section className={`panel border-t-4 ${color === "blue" ? "border-t-blue" : "border-t-slate-400"} p-5`}><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-lg ${color === "blue" ? "bg-blue/10 text-blue" : "bg-slate-100 text-slate-600"}`}>{icon}</span><button disabled={busy} onClick={onRun} className={`rounded-lg px-4 py-2 text-xs font-semibold text-white disabled:opacity-50 ${color === "blue" ? "bg-blue" : "bg-slate-700"}`}>{running ? "Running…" : metrics ? "Run again" : "Run strategy"}</button></div><h2 className="mb-0 mt-4 text-lg font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">{text}</p>{metrics ? <div className="mt-5 grid grid-cols-3 gap-3"><Metric name="Simulated recovered" value={inr(metrics.revenueRecovered)}/><Metric name="Value recovery" value={pct(metrics.recoveryRateByValue)}/><Metric name="Attempts" value={String(metrics.attempts)}/><Metric name="Recovered cases" value={String(metrics.recoveredCount)}/><Metric name="Contacts" value={String(metrics.customerContacts)}/><Metric name="Escalations" value={String(metrics.escalations)}/></div> : <div className="mt-5 rounded-lg bg-slate-50 p-6 text-center text-xs text-slate-400">Not run yet</div>}</section>; }
function Metric({ name, value, positive = false }: { name: string; value: string; positive?: boolean }) { return <div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] text-slate-400">{name}</div><div className={`metric-number mt-1 text-lg font-semibold ${positive ? "text-emerald-700" : ""}`}>{value}</div></div>; }
function GoldenLink({ href, title, text, tone, ready }: { href: string; title: string; text: string; tone: "success" | "danger"; ready: boolean }) { return <Link href={ready ? href : "/command-center"} aria-disabled={!ready} className={`panel flex items-center justify-between border-l-4 p-5 ${tone === "success" ? "border-l-emerald-500" : "border-l-red-500"} ${ready ? "hover:bg-slate-50" : "opacity-60"}`}><div><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs text-slate-500">{ready ? text : "Run RecoverAI to materialize this case."}</div></div><span className="text-slate-300">→</span></Link>; }
